# Generated by Django 5.2.9 on 2025-12-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_curator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
