# Generated by Django 5.2.9 on 2025-12-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_curator', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=13, unique=True)),
                ('summary_reviews', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
