# Generated by Django 5.2.9 on 2025-12-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_curator', '0003_aireviewanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireviewanalysis',
            name='story_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
