# Generated by Django 5.2.9 on 2025-12-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_curator', '0004_aireviewanalysis_story_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireviewanalysis',
            name='author_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aireviewanalysis',
            name='author_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aireviewanalysis',
            name='recommend_targets',
            field=models.JSONField(default=list),
        ),
    ]
