# Generated by Django 5.2.9 on 2025-12-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_curator', '0005_aireviewanalysis_author_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aireviewanalysis',
            old_name='author_intro',
            new_name='author_info',
        ),
        migrations.AddField(
            model_name='aireviewanalysis',
            name='author_works',
            field=models.JSONField(default=list),
        ),
    ]
