# Generated by Django 5.2.9 on 2025-12-22 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grassdaily',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='grassdaily',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='grassdaily',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='grassdaily',
            index=models.Index(fields=['user', 'date'], name='grass_grass_user_id_2da321_idx'),
        ),
    ]
