# Generated by Django 5.2.9 on 2025-12-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_representative',
            field=models.BooleanField(default=False),
        ),
    ]
