# Generated by Django 5.2.9 on 2025-12-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('cover', models.URLField(blank=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('best_seller_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('author_info', models.TextField(blank=True)),
                ('author_works', models.JSONField(blank=True, null=True)),
                ('author_image', models.URLField(blank=True)),
                ('author_source', models.CharField(choices=[('wiki', 'Wikipedia'), ('ai', 'AI')], default='ai', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
