# Generated by Django 5.2.9 on 2025-12-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='best_seller_rank',
            new_name='best_rank',
        ),
    ]
