# Generated by Django 5.2.9 on 2025-12-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_info',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_source',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_works',
        ),
        migrations.RemoveField(
            model_name='book',
            name='best_rank',
        ),
    ]
