# Generated by Django 5.2.9 on 2025-12-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bestsellersync'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=255)),
                ('mall_type', models.CharField(max_length=20)),
                ('item_id', models.IntegerField(unique=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('cover', models.URLField()),
                ('best_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('sales_point', models.PositiveIntegerField(default=0)),
                ('customer_review_rank', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'ordering': ['best_rank', '-sales_point', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NewSpecialSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
