# Generated by Django 5.2.9 on 2025-12-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_newspecial_newspecialsync'),
    ]

    operations = [
        migrations.CreateModel(
            name='AladinListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('Bestseller', 'Bestseller'), ('ItemNewSpecial', 'ItemNewSpecial'), ('ItemNewAll', 'ItemNewAll'), ('ItemEditorChoice', 'ItemEditorChoice')], max_length=30)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('mall_type', models.CharField(blank=True, max_length=20)),
                ('item_id', models.IntegerField()),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('isbn13', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cover', models.URLField(blank=True)),
                ('best_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('sales_point', models.PositiveIntegerField(default=0)),
                ('customer_review_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AladinSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(max_length=30, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bestsellers',
        ),
        migrations.DeleteModel(
            name='BestsellerSync',
        ),
        migrations.DeleteModel(
            name='NewSpecialSync',
        ),
        migrations.AddConstraint(
            model_name='aladinlistitem',
            constraint=models.UniqueConstraint(fields=('query_type', 'item_id'), name='unique_item_per_query_type'),
        ),
    ]
