# Generated by Django 5.2.9 on 2025-12-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_aladinlistitem_aladinsync_delete_bestsellers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewSpecial',
        ),
        migrations.AlterModelOptions(
            name='aladinlistitem',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveConstraint(
            model_name='aladinlistitem',
            name='unique_item_per_query_type',
        ),
        migrations.AlterField(
            model_name='aladinlistitem',
            name='best_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aladinlistitem',
            name='customer_review_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aladinlistitem',
            name='query_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aladinlistitem',
            name='sales_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aladinlistitem',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aladinsync',
            name='query_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='aladinlistitem',
            constraint=models.UniqueConstraint(fields=('query_type', 'item_id'), name='uniq_querytype_itemid'),
        ),
    ]
