# Generated by Django 5.2.9 on 2025-12-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_newspecial_alter_aladinlistitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='customer_review_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
