# Generated by Django 5.2.9 on 2025-12-19 18:15

from django.db import migrations


def seed_communities(apps, schema_editor):
    Community = apps.get_model("community", "Community")

    defaults = [
        ("KR", "한국"),
        ("JP", "일본"),
        ("CN", "중화권"),
        ("EN", "영미권"),
    ]

    for country, name in defaults:
        Community.objects.update_or_create(
            country=country,
            defaults={"name": name},
        )

class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_alter_community_options_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_communities),
    ]
