# Generated by Django 5.2.9 on 2025-12-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_post_options_remove_post_community_board_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['key']},
        ),
        migrations.RemoveConstraint(
            model_name='board',
            name='unique_board_per_community',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='slug',
            new_name='key',
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('community', 'key'), name='unique_board_per_community'),
        ),
    ]
