# Generated by Django 5.2.9 on 2025-12-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_board_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['slug']},
        ),
        migrations.RemoveConstraint(
            model_name='board',
            name='unique_board_per_community',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='key',
            new_name='slug',
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('community', 'slug'), name='unique_board_per_community'),
        ),
    ]
