# Generated by Django 5.2.9 on 2025-12-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_genre',
            field=models.CharField(blank=True, choices=[('novel_poem_drama', '소설/시/희곡'), ('business', '경제/경영'), ('self_help', '자기계발'), ('humanities', '인문/교양'), ('comic_ebook', '만화/eBook'), ('science', '과학')], max_length=20, null=True),
        ),
    ]
