# Generated by Django 5.2.9 on 2025-12-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_country',
            field=models.CharField(blank=True, choices=[('KR', '한국'), ('JP', '일본'), ('ZH', '중화권'), ('US', '미국'), ('UK', '영국'), ('OTHER', '기타')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_genre',
            field=models.CharField(blank=True, choices=[('novel', '소설'), ('comic', '만화'), ('essay', '에세이'), ('issue', '시사·이슈'), ('etc', '기타')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
