# Generated by Django 5.2.9 on 2025-12-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
