# Generated by Django 5.2.9 on 2025-12-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='exp',
            new_name='exp_total',
        ),
    ]
